-- create database BODEGA;

Use BODEGA;

CREATE TABLE PRODUCTOS (
ID INT NOT NULL PRIMARY KEY auto_increment ,
NOMBRE varchar(28),
PRECIO float,
PROVEEDOR VARCHAR(28)
);

DESC PRODUCTOS;

SELECT * FROM PRODUCTOS;

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROVEEDOR)
VALUES
	("CAFE", 3.99, "LUCKY_LUCAS_CA");
    
SELECT * FROM PRODUCTOS;

INSERT INTO PRODUCTOS (NOMBRE, PRECIO, PROVEEDOR)
VALUES
	("HARINA DE TRIGO", 1.75, "PADRE_LUCAS_CA"),
    ("GASEOSA", 1.50, "ABUELO_LUCAS_CA"),
    ("MANTEQUILLA", 2, "MILANAT"),
    ("GALLETAS DE VAINILLA", 2, "DELICIAS_JOSELE",
    ("ENCENDEDORES", 0.9, "LUCKY_LUCAS_CA"),
    ("LECHE", 1.75, "MILANAT"),
    ("GOMITAS", 0.9, "CHUCHU_ELDUCE")
    ;
    
	
    

    
